// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpacmjjbdfjtfrxrimev.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwYWNtampiZGZqdGZyeHJpbWV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NzczMTcsImV4cCI6MjA3MjM1MzMxN30.0kE6MsNq4PuG-QsOHJZXwEir7iJ6D8mTTQ-8SX79JE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});